### ISSUE TITLE
Z-fighting in GLQuake

### ISSUE THREAD

**Issue by leahanderson1** [GMH-Code/Quake-WASM#5] opened 2023-11-15 19:13 UTC
![image](https://github.com/GMH-Code/Quake-WASM/assets/144633084/0934b0a5-2b5b-453b-8a27-c9233f35f1ff)

**Comment by GMH-Code** [comment] 2023-11-16 10:14
Hi @OtterCodes102

Thanks for reporting the issue.  I'm amazed I didn't spot that quite obvious Z-fighting when testing -- there is a Quad Damage secret right next to where you are stood, and the flickering in the corner is quite obvious!

I'll take a look at it.

**Comment by GMH-Code** [comment] 2023-11-16 10:45
Okay, so I loaded up old Windows GLQuake.  I can verify this exact glitch occurs in the original game.  Amazing -- after all those years -- I either never noticed, forgot about it, or just 'forgave' GLQuake as the hardware rendering was new and a very-nice-to-have at the time.

One objective of the project was to preserve the original game as closely as possible.  I've been tempted to add features, make the game look better, lift limits and more, but there is a conflict of interest regarding consistently retaining the engine's performance in WASM on lower-performance systems, or putting people off playing the port because it's not exactly the same as the original.  Fixing this Z-fighting may also result in visual glitches in other areas.

I'll see if it's fixable outside of map rebuilding anyway, but as it's in the original, I may opt to leave it as-is.

**Comment by GMH-Code** [comment] 2023-11-16 15:16
It appears as though there aren't many locations in the game where this happens.  As I expected it's down to a problem in map design, and the issue is compiled into the official BSP files, which are in turn embedded into the official PAK files, which I can't correct for legal reasons.

The problem also seems to be there in the software renderer, but you don't see it due to limitations of the renderer itself.

Since the original game has this glitch, and correcting it in the code could cause rendering issues affecting other parts of the game, I'll leave it as-is.

**Comment by GMH-Code** [comment] 2023-11-16 15:17
Re-closing as 'won't fix' for the above reason.

**Closed as not planned by GMH-Code** 2023-11-16 15:16 UTC
